### ISSUE TITLE
[Spell /Raid] Waterlogged -Twilight Ascendant Council / Feludius - The Bastion of Twilight

### ISSUE THREAD

**Issue by Bloodborne93** [WoWManiaUK/Blackwing-Lair#3582]
**Links:**
https://www.wowhead.com/npc=43687/feludius
https://www.wowhead.com/spell=82762/waterlogged

**What is happening:**
I received the debuff  "Waterlogged" from Feludius, I went over the flame, but nothing happens because it can't be dispelled by it.
![Bug](https://user-images.githubusercontent.com/52720024/66498929-2e6c1880-eabf-11e9-8761-80cec636e081.jpg)

**What should happen:**
Staying above the flames, the debuff should be disappear.

**Comment by Rushor** [comment]
will check

**Comment by Rushor** [comment]
removal fixed with next update

![I](https://i.imgur.com/vrTAJJG.jpg)
![I](https://i.imgur.com/rwb88HZ.jpg)

**Comment by Slydee23** [comment]
reopen pls. still not working testet 20 mins ago

**Comment by Sammy974** [comment]
It should be tested with different classes and races because it seems that it works for some players and not for others. For example it works with my druid and dk, but not with my paladin.

**Comment by APTX4869s** [comment]
as a paladin, sometimes it got removed from me and sometimes not.
So what I've noticed that if you got hit twice from the water, the debuff won't get dispelled by the flames. ( still not sure about it )

**Comment by Rushor** [comment]
okay next try. i increased the spelleffect of Inferno Rush (82860)

**Comment by Slydee23** [comment]
you tried it with different races/classes ?

**Comment by Sammy974** [comment]
Still not working :(

**Comment by Bloodborne93** [comment]
WE HAVE FIND THE PROBLEM. The problem are the adds before the boss, we don't know what they are doing, but if you kill them and then relog, cancel the cache.. puff the game is done!. Flames remove the waterlogged debuff. we have checked it right now 18/10/2019 23:16.

**Comment by Rushor** [comment]
okay what?
is it working then?
i do not understand the relation to the adds

**Comment by Rushor** [comment]
a spell from the adds was the reason. next update it will work again.
